package com.chvma.wordfight.localization

enum class AppLanguage(
    val code: String,
    val nativeName: String,
) {
    EN("en", "English"),
    RU("ru", "Русский"),
    UA("uk", "Українська"),
    FR("fr", "Français"),
    ES("es", "Español"),
    ;

    companion object {
        val supported = listOf(EN, RU, UA, FR, ES)

        fun fromCode(code: String?): AppLanguage {
            return supported.firstOrNull { it.code == code } ?: EN
        }
    }
}

data class AppStrings(
    val appTitle: String,
    val bestLabel: String,
    val scoreLabel: String,
    val tapToStart: String,
    val myWords: String,
    val languages: String,
    val gameOver: String,
    val missedWords: String,
    val noSavedWords: String,
    val home: String,
    val playAgain: String,
    val selectLanguage: String,
    val reviveLifeTitle: String,
    val reviveLifeMessage: String,
    val watchVideo: String,
    val noThanks: String,
    val leaderboard: String,
    val leaderboardToday: String,
    val leaderboardAllTime: String,
    val leaderboardLoading: String,
    val leaderboardEmpty: String,
    val leaderboardLanguage: String,
    val onboardingTitle: String,
    val onboardingNameLabel: String,
    val onboardingNamePlaceholder: String,
    val onboardingLanguageLabel: String,
    val onboardingConfirm: String,
)

object Localization {
    fun strings(language: AppLanguage): AppStrings {
        return when (language) {
            AppLanguage.EN -> AppStrings(
                appTitle = "Pronounce Word!",
                bestLabel = "Best",
                scoreLabel = "Score",
                tapToStart = "Tap to start!",
                myWords = "My words",
                languages = "Languages",
                gameOver = "Game Over",
                missedWords = "Missed words",
                noSavedWords = "No saved words yet",
                home = "Home",
                playAgain = "Play Again",
                selectLanguage = "Select language",
                reviveLifeTitle = "Restore one life?",
                reviveLifeMessage = "Watch a rewarded video to continue.",
                watchVideo = "Watch video",
                noThanks = "No, results",
                leaderboard = "Rating",
                leaderboardToday = "Today",
                leaderboardAllTime = "All time",
                leaderboardLoading = "Loading...",
                leaderboardEmpty = "No players yet",
                leaderboardLanguage = "Language",
                onboardingTitle = "How should we call you in the rating?",
                onboardingNameLabel = "Name",
                onboardingNamePlaceholder = "Enter your name",
                onboardingLanguageLabel = "Language",
                onboardingConfirm = "Continue",
            )
            AppLanguage.RU -> AppStrings(
                appTitle = "Произнеси слово!",
                bestLabel = "Ваш лучший результат",
                scoreLabel = "Счет",
                tapToStart = "Нажми, чтобы начать!",
                myWords = "Мои слова",
                languages = "Языки",
                gameOver = "Игра окончена",
                missedWords = "Пропущенные слова",
                noSavedWords = "Сохраненных слов пока нет",
                home = "Главная",
                playAgain = "Играть снова",
                selectLanguage = "Выберите язык",
                reviveLifeTitle = "Хотите восстановить одну жизнь?",
                reviveLifeMessage = "Посмотрите рекламное видео и продолжите игру.",
                watchVideo = "Посмотреть видео",
                noThanks = "Нет, результат",
                leaderboard = "Рейтинг",
                leaderboardToday = "За день",
                leaderboardAllTime = "За все время",
                leaderboardLoading = "Загрузка...",
                leaderboardEmpty = "Пока нет игроков",
                leaderboardLanguage = "Язык",
                onboardingTitle = "Как вас назвать в рейтинге?",
                onboardingNameLabel = "Имя",
                onboardingNamePlaceholder = "Введите имя",
                onboardingLanguageLabel = "Язык",
                onboardingConfirm = "Продолжить",
            )
            AppLanguage.UA -> AppStrings(
                appTitle = "Назви слово!",
                bestLabel = "Найкращий",
                scoreLabel = "Рахунок",
                tapToStart = "Натисни, щоб почати!",
                myWords = "Мої слова",
                languages = "Мови",
                gameOver = "Гру завершено",
                missedWords = "Пропущені слова",
                noSavedWords = "Збережених слів поки немає",
                home = "Головна",
                playAgain = "Грати знову",
                selectLanguage = "Оберіть мову",
                reviveLifeTitle = "Хочете відновити одне життя?",
                reviveLifeMessage = "Перегляньте рекламне відео та продовжуйте гру.",
                watchVideo = "Переглянути відео",
                noThanks = "Ні, результат",
                leaderboard = "Рейтинг",
                leaderboardToday = "За день",
                leaderboardAllTime = "За весь час",
                leaderboardLoading = "Завантаження...",
                leaderboardEmpty = "Поки немає гравців",
                leaderboardLanguage = "Мова",
                onboardingTitle = "Як вас називати в рейтингу?",
                onboardingNameLabel = "Ім'я",
                onboardingNamePlaceholder = "Введіть ім'я",
                onboardingLanguageLabel = "Мова",
                onboardingConfirm = "Продовжити",
            )
            AppLanguage.FR -> AppStrings(
                appTitle = "Prononcer le mot!",
                bestLabel = "Meilleur",
                scoreLabel = "Score",
                tapToStart = "Appuie pour commencer !",
                myWords = "Mes mots",
                languages = "Langues",
                gameOver = "Fin de partie",
                missedWords = "Mots manqués",
                noSavedWords = "Aucun mot enregistré pour l'instant",
                home = "Accueil",
                playAgain = "Rejouer",
                selectLanguage = "Choisir la langue",
                reviveLifeTitle = "Récupérer une vie ?",
                reviveLifeMessage = "Regardez une vidéo récompensée pour continuer.",
                watchVideo = "Voir la vidéo",
                noThanks = "Non, résultat",
                leaderboard = "Classement",
                leaderboardToday = "Aujourd'hui",
                leaderboardAllTime = "Global",
                leaderboardLoading = "Chargement...",
                leaderboardEmpty = "Aucun joueur",
                leaderboardLanguage = "Langue",
                onboardingTitle = "Comment vous appeler dans le classement ?",
                onboardingNameLabel = "Nom",
                onboardingNamePlaceholder = "Entrez votre nom",
                onboardingLanguageLabel = "Langue",
                onboardingConfirm = "Continuer",
            )
            AppLanguage.ES -> AppStrings(
                appTitle = "Pronunciar palabra!",
                bestLabel = "Mejor",
                scoreLabel = "Puntuación",
                tapToStart = "Toca para empezar!",
                myWords = "Mis palabras",
                languages = "Idiomas",
                gameOver = "Fin del juego",
                missedWords = "Palabras perdidas",
                noSavedWords = "Aún no hay palabras guardadas",
                home = "Inicio",
                playAgain = "Jugar de nuevo",
                selectLanguage = "Elige idioma",
                reviveLifeTitle = "¿Recuperar una vida?",
                reviveLifeMessage = "Mira un video con recompensa para continuar.",
                watchVideo = "Ver video",
                noThanks = "No, resultado",
                leaderboard = "Clasificacion",
                leaderboardToday = "Hoy",
                leaderboardAllTime = "Historico",
                leaderboardLoading = "Cargando...",
                leaderboardEmpty = "Aun no hay jugadores",
                leaderboardLanguage = "Idioma",
                onboardingTitle = "¿Como te llamamos en la clasificacion?",
                onboardingNameLabel = "Nombre",
                onboardingNamePlaceholder = "Ingresa tu nombre",
                onboardingLanguageLabel = "Idioma",
                onboardingConfirm = "Continuar",
            )
        }
    }
}
