package com.chvma.wordfight.content

import com.chvma.wordfight.model.WordContent

object WordRepository {
    val words: List<WordContent> = listOf(
        WordContent(1, "suitcase", "чемодан", 1),
        WordContent(2, "newspaper", "газета", 1),
        WordContent(3, "camera", "фотоаппарат", 1),
        WordContent(4, "bridge", "мост", 1),
        WordContent(5, "stairs", "лестница", 1),
        WordContent(6, "umbrella", "зонт", 1),
        WordContent(7, "wallet", "бумажник", 1),
        WordContent(8, "mirror", "зеркало", 1),
        WordContent(9, "pillow", "подушка", 1),
        WordContent(10, "knife", "нож", 1),
        WordContent(11, "bottle", "бутылка", 1),
        WordContent(12, "glass", "стакан", 1),
        WordContent(13, "water", "вода", 1),
        WordContent(14, "ladder", "стремянка", 1),
        WordContent(15, "envelope", "конверт", 1),
        WordContent(16, "stamp", "марка", 1),
        WordContent(17, "wheel", "колесо", 1),
        WordContent(18, "flag", "флаг", 1),
        WordContent(19, "key", "ключ", 1),
        WordContent(20, "brush", "кисть", 1),
        WordContent(21, "scissors", "ножницы", 1),
        WordContent(22, "climb", "забираться", 1),
        WordContent(23, "drop", "ронять", 1),
        WordContent(24, "push", "толкать", 1),
        WordContent(25, "pull", "тянуть", 1),
        WordContent(26, "break", "ломать", 1),
        WordContent(27, "build", "строить", 2),
        WordContent(28, "cubes", "кубики", 2),
        WordContent(29, "carry", "нести", 2),
        WordContent(30, "catch", "ловить", 2),
        WordContent(31, "shelf", "полка", 2),
        WordContent(32, "curtain", "штора", 2),
        WordContent(33, "carpet", "ковер", 2),
        WordContent(34, "bucket", "ведро", 2),
        WordContent(39, "comb", "расческа", 2),
        WordContent(40, "toothbrush", "зубная щетка", 2),
        WordContent(41, "soap", "мыло", 2),
        WordContent(42, "iron", "утюг", 2),
        WordContent(43, "toaster", "тостер", 2),
        WordContent(44, "kettle", "чайник", 2),
        WordContent(45, "plate", "тарелка", 2),
        WordContent(46, "spoon", "ложка", 2),
        WordContent(47, "fork", "вилка", 2),
        WordContent(48, "pan", "сковорода", 2),
        WordContent(51, "oven", "духовка", 2),
        WordContent(52, "washing machine", "стиральная машина", 2),
        WordContent(53, "vacuum cleaner", "пылесос", 2),
        WordContent(54, "hammer", "молоток", 2),
        WordContent(50, "screwdriver", "отвертка", 2),
        WordContent(49, "nail", "гвоздь", 2),
        WordContent(55, "needle", "иголка", 2),
        WordContent(57, "thread", "нитка", 2),
        WordContent(56, "button", "пуговица", 2),
        WordContent(58, "coin", "монета", 2),
        WordContent(59, "battery", "батарейка", 2),
        WordContent(60, "candle", "свеча", 2),
        WordContent(61, "match", "спичка", 3),
        WordContent(63, "clock", "часы", 3),
        WordContent(64, "calendar", "календарь", 3),
        WordContent(65, "diary", "дневник", 3),
        WordContent(66, "notebook", "тетрадь", 3),
        WordContent(67, "pencil", "карандаш", 3),
        WordContent(68, "ruler", "линейка", 3),
        WordContent(69, "eraser", "ластик", 3),
        WordContent(70, "sharpener", "точилка", 3),
        WordContent(76, "compass", "компас", 3),
        WordContent(71, "backpack", "рюкзак", 3),
        WordContent(73, "balloon", "воздушный шар", 3),
        WordContent(75, "tent", "палатка", 3),
        WordContent(77, "flashlight", "фонарик", 3),
        WordContent(78, "binoculars", "бинокль", 3),
        WordContent(81, "life jacket", "спасательный жилет", 3),
        WordContent(82, "anchor", "якорь", 3),
        WordContent(65, "paddle", "весло", 3),
        WordContent(79, "fishing rod", "удочка", 3),
        WordContent(80, "net", "сеть", 3),
        WordContent(83, "helmet", "шлем", 3),
        WordContent(84, "goggles", "защитные очки", 3),
        WordContent(85, "gloves", "перчатки", 3),
        WordContent(86, "boots", "ботинки", 3),
    )

    fun forLevel(level: Int): List<WordContent> = words.filter { it.level <= level }
}
